@startuml

: user provides a data;

if (find by name) then (yes)
    :system look for the name in the animalsList;

    if(animal found) then (yes)
        :system return the animal;
        end;
    else (no)
        : the animal bestaat niet in the shelter;
        end;
    endif
else (no)
   if(find by IDNumber) then (yes)
    :system look at for animal by IDNumber in the animalsList;
    if(animal found) then (yes)
        :system return the animal;
        end;
    else (no)
        : the animal bestaat niet in the shelter;
        end;
    endif
    else(no)
     :error can only by name or IDNumber;
        end;
@enduml