@startuml

User -> AnimalShelterApp : User request
AnimalShelterApp -> AnimalService : getAllAnimals()
AnimalService -> AnimalRepository : getAnimals()

AnimalService <-- AnimalRepository : List<Animal> animals
AnimalShelterApp <-- AnimalService : List<Animal> animals
User <-- AnimalShelterApp : List<Animal> animals

@enduml