@startuml

User -> AnimalShelterApp : input animal
AnimalShelterApp -> AnimalService : addAnimal(Animal: animal)
AnimalService -> AnimalRepository : getAnimal()

alt already in the shelter
AnimalService <-- AnimalRepository : Animal
AnimalShelterApp <-- AnimalService : void
User <-- AnimalShelterApp : error message

else not in the shelter
AnimalService <-- AnimalRepository : null
AnimalService -> AnimalRepository : addAnimal()
AnimalShelterApp <-- AnimalService : void
User <-- AnimalShelterApp : ok message

end
@enduml