@startuml

User -> AnimalShelterApp : input animal
AnimalShelterApp -> AnimalService : addAnimal(Animal: animal)
AnimalService -> AnimalRepository : addAnimal(Animal : animal)

alt already in the shelter
AnimalService <-- AnimalRepository : error
AnimalShelterApp <-- AnimalService : error
User <-- AnimalShelterApp : error message

else not in the shelter

AnimalService <-- AnimalRepository :  void
AnimalShelterApp <-- AnimalService : void
User <-- AnimalShelterApp : ok message

end
@enduml