@startuml

start
:user inputs name or id animal;
if(user inputs name) then (yes)
   :system retrieves animal by name;
   if (are there animals) then (yes)
        if (is there more than 1 animal) then (yes);
            :error too many animals;
            end;
        else (no)
        endif
   else(no)
        :error no animals found;
        end;
   endif
else(no, uses id)
    :system retrieves animal by id;
    if (is the animal found) then (yes)
    else (no)
        :error no animals found;
        end;
    endif;
endif
:return the found animal;
stop;
@enduml

le plus lisible serait d'avoir une répétition de chaque côté.