@startuml
User -> AnimalShelterApp : input name or id

alt treat by name
AnimalShelterApp -> AnimalService : treatAnimal(String:name)
AnimalService -> AnimalRepository : getAnimal(String:name)
note right of AnimalRepository : is merdere name?

else treat by ID
AnimalShelterApp -> AnimalService : treatAnimal(int:id)
AnimalService -> AnimalRepository : getAnimal((int:id)

end

AnimalService <--AnimalRepository : optional<Animal>

alt isPresent
AnimalService -> AnimalService : treatAnimal()
note right of AnimalService : - clean()\n- vaccinate
AnimalShelterApp <-- AnimalService : void
User <-- AnimalShelterApp : OK message

else isEmpty
AnimalShelterApp <-- AnimalService : error
User <-- AnimalShelterApp : error message
end
@enduml